name: Interview task 2025

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: interview-task-2025
          path: target/interview-task-2025.jar
